spring:
  application:
    name: testeCaju
  banner:
    location: banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/autorizador
    username: autorizador
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
